language: node_js

env:
     - DB=postgresql://postgres@localhost:5432/greeted_app_database
     
node_js:  
   - "8.9.4"
        
before_script:
  - psql -c 'create database greeted_app_database' -U postgres
  - psql -U postgres -d greeted_app_database -a -f tables.sql

addons:
    apt:
    packages:
    - postgresql-server-dev-9.2
